---
- hosts: localhost

  vars:
    app_store_apps:
      - 1295203466 # Microsoft Remote Desktop

  tasks:
    - loop: '{{ app_store_apps }}'
      name: Install default App Store applications
      ignore_errors: true
      community.general.mas:
        id: '{{ item }}'
        state: present