---
- hosts: localhost

  tasks:
    - name: Install Cyberduck with Homebrew
      community.general.homebrew_cask:
        name: cyberduck
        state: present
    - name: Install TeamViewer with Homebrew
      community.general.homebrew_cask:
        name: teamviewer
        state: present