---
- hosts: localhost

  tasks:
    - name: Install App Store Applications
      community.general.mas:
        id:
          - 409183694 # Keynote
          - 409201541 # Pages
          - 409203825 # Numbers
          - 1451685025 # WireGuard
          - 985367838 # Microsoft Outlook
          - 462054704 # Microsoft Word
          - 462058435 # Microsoft Excel
          - 462062816 # Microsoft PowerPoint
          - 823766827 # OneDrive
        state: latest

    - name: Upgrade all installed Mac App Store Apps
      community.general.mas:
        upgrade_all: true