---
- hosts: localhost

  vars:
    brew_cask_apps:
      - google-chrome
      - microsoft-teams
      - 1password
      - tunnelblick
      - cleanmymac
      - raycast
      - alt-tab
      - rectangle
      - keka
      - adobe-acrobat-reader
#    brew_apps:
#      - ...

  tasks:
    - loop: '{{ brew_cask_apps }}'
      name: Installing Homebrew cask apps
      ignore_errors: true
      community.general.homebrew_cask:
        name: '{{ item }}'
        state: present
#    - loop: '{{ brew_apps }}'
#      name: Installing Homebrew apps
#      ignore_errors: true
#      community.general.homebrew:
#        name: '{{ item }}'
#        state: present



