---
- hosts: localhost

  tasks:
    - name: Install App Store Applications
      community.general.mas:
        id:
          - 497799835 # Xcode
          - 1085114709 # Parallels Desktop
#          - 429449079 # Patterns - The Regex App
        state: present