---
- hosts: localhost

  vars:
    app_store_apps:
      - 497799835 # Xcode
      - 1085114709 # Parallels Desktop
#     - 429449079 # Patterns - The Regex App

  tasks:
    - loop: '{{ app_store_apps }}'
      name: Install default App Store applications
      ignore_errors: true
      community.general.mas:
        id: '{{ item }}'
        state: present
