---
- hosts: localhost

  vars:
    brew_cask_apps:
      - unity
      - jetbrains-toolbox
      - sublime-text
      - docker
      - postman
      - gas-mask
      - vysor
      - firefox
      - fnm
    brew_apps:
      - fvm

  tasks:
    - name: Tap the fvm Homebrew repository
      ignore_errors: true
      community.general.homebrew_tap:
        name: leoafarias/fvm
    - loop: '{{ brew_cask_apps }}'
      name: Installing Homebrew cask apps
      ignore_errors: true
      community.general.homebrew_cask:
        name: '{{ item }}'
        state: present
    - loop: '{{ brew_apps }}'
      name: Installing Homebrew apps
      ignore_errors: true
      community.general.homebrew:
        name: '{{ item }}'
        state: present
